image: node:12

pipelines:
  default:
    # - step:
    #     name: Build
    #     caches:
    #       - node
    #     script:
    #       - npm install
    #       - npm run build
    - step:
        name: Deploy
        script:
          - npm install
          - echo $CERTIFICATE > server.cer
          - export NODE_EXTRA_CA_CERTS=./server.cer
          - cat ./server.cer
          - npm run deploy
        caches:
          - node

